# Python for R users
# Part 6: Linear algebra and statistical modeling


Here are some great resources (from which some of the material below was adapted):
- https://github.com/kuleshov/cs228-material/blob/master/tutorials/python/cs228-python-tutorial.ipynb
- https://cs231n.github.io/python-numpy-tutorial/#numpy

First we need to tell Jupyter to let us use R within this Python notebook, and load some relevant libraries

In [116]:
import numpy
import pandas
import statsmodels.api

%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


## Creating matrices in Numpy

First let's refresh a bit on numpy matrices and look at the various functions that are available to work with them.  Note that as we discussed in an earlier section, Numpy has two types of objects that can represent a numeric matrix: arrays and matrices. Because Numpy matrices are not used very often, we will focus here on arrays, so when I used the term "matrix" I am really referring to "a 2-dimensional numpy.array object".

Let's create a matrix ```X```:

$X = \begin{bmatrix}
1 & 5\\ 
2 & 6\\ 
3 & 7\\ 
4 & 8
\end{bmatrix}$

In [7]:
X = numpy.array([[1, 5], [2, 6], [3, 7], [4, 8]])
X

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [5]:
X.shape

(4, 2)

Let's say that we want to create a matrix with a single column called ```Y```:

$Y = \begin{bmatrix}
8\\ 
10\\ 
12\\ 
14
\end{bmatrix}$



If we just create a vector, it will only have a single dimension:

In [10]:
Y_vector = numpy.array([8, 10, 12, 14])
Y_vector.shape

(4,)

You might think that transposing it would turn it into a column vector, but that doesn't work:

In [11]:
Y_vector.T

array([ 8, 10, 12, 14])

In [12]:
Y_vector.T.shape

(4,)

There are a couple of ways around this.  First, we could specify it as a set of vectors:

In [17]:
Y = numpy.array([[8], [10], [12], [14]])
Y

array([[ 8],
       [10],
       [12],
       [14]])

We could also create a vector and then turn it into a matrix by adding a dimension:

In [20]:
Y = numpy.array([ 8, 10, 12, 14])  # create a vector
print(Y)

Y = Y[:, numpy.newaxis]  # add a new axis using numpy.newaxis
print(Y)

[ 8 10 12 14]
[[ 8]
 [10]
 [12]
 [14]]


There are also a number of ways to create full matrices in Numpy:

In [36]:
numpy.zeros((4, 4))  # create a matrix full of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
numpy.ones((4, 4))  # create a matrix full of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
numpy.eye(4)  # create a identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
numpy.random.randn(4, 4)  # create a matrix of random normal variates

array([[ 0.07745061, -0.18132854,  1.14380771,  0.15858806],
       [ 0.80841882, -0.64581488,  1.84212199,  1.20836525],
       [ 1.22670288,  1.4361737 ,  0.81077107,  0.55930126],
       [ 0.8419945 , -0.62126735,  0.87026206,  0.9736254 ]])

Finally, we can take a vector and reshape it into a matrix using the ```.reshape()``` operator

In [44]:
numpy.random.randn(16).reshape((4, 4)) # create a 16 item vector and reshape into a 4 x 4 array

array([[ 0.58890519,  1.47946945, -0.30811304, -1.92770671],
       [ 0.61598558,  1.22105069, -0.46318886,  0.91614638],
       [ 0.63697573,  0.21707719, -0.39858465, -0.39221386],
       [-0.73307617, -0.13088766, -0.4658867 ,  1.41455679]])

## Basic arithmetic on matrices

All of the standard aritmetic and logical operators work on matrices in Numpy, operating element-wise.



In [50]:
A = numpy.ones((3,3)) * 2
print(A)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [51]:
B = numpy.arange(1,10).reshape(3,3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
A + B  # elementwise addition

array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [53]:
A - B  # elementwise subtraction

array([[ 1.,  0., -1.],
       [-2., -3., -4.],
       [-5., -6., -7.]])

In [54]:
A * B  # elementwise multiplication

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [56]:
A / B  # elementwise division

array([[2.        , 1.        , 0.66666667],
       [0.5       , 0.4       , 0.33333333],
       [0.28571429, 0.25      , 0.22222222]])

In [58]:
A == B  # elementwise equality

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

## Matrix multiplication

Matrix multiplication is performed in Numpy using the ```.dot()``` operator.  

First let's look at a simple example: the inner product of two matrices (aka the "dot product").  

In [73]:
A = numpy.array([[1, 2, 3, 4]])
print(A.shape)
A

(1, 4)


array([[1, 2, 3, 4]])

In [74]:
B = numpy.array([[5, 6, 7, 8]]).T
print(B.shape)
B

(4, 1)


array([[5],
       [6],
       [7],
       [8]])

In [75]:
dp = A.dot(B)
dp

array([[70]])

Note that the ```.dot()``` operator returns a single value (i.e. a *scalar*) but it returns it in the form of a matrix.  Thus, if we wanted to work with that value we would need to reference it in the matrix:

In [76]:
dp[0, 0]

70

The ```.dot()``` operator also performs matrix multiplication

In [77]:
I = numpy.eye(B.shape[0])
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
I.dot(B)  # multiply by identity to get original matrix

array([[5.],
       [6.],
       [7.],
       [8.]])

## Matrix inversion

Matrix inversion for square matrices (when possible) can be performed using the ```numpy.linalg.inv()``` function.

In [87]:
I = numpy.eye(4)
numpy.linalg.inv(I)  # inverse of an identity is itself

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Often in statistics we need to compute the pseudo-inverse of a matrix that is not square.  We can do that using the ```numpy.linalg.pinv()``` function

In [88]:
R = numpy.random.randn(6, 4)
R

array([[-0.57344016,  1.07747937, -0.50876169, -1.86218524],
       [ 0.0114388 , -0.02775375,  0.10517914, -0.38024641],
       [ 0.66925415, -1.08451724,  1.05243413,  0.34458032],
       [ 2.0575053 , -0.09195579, -1.54825252,  0.7635312 ],
       [-0.60547741, -0.46430286,  0.51902325,  1.8179072 ],
       [ 0.33913747,  0.80691863, -0.17380382,  2.25232951]])

In [92]:
pinv = numpy.linalg.pinv(R)
pinv

array([[ 0.07335528,  0.10388678,  0.5221196 ,  0.13659959, -0.48529086,
         0.34369183],
       [ 0.3710633 ,  0.08452705,  0.19836166, -0.214768  , -0.45230208,
         0.72858055],
       [ 0.11667684,  0.13872055,  0.69457962, -0.40039239, -0.42496194,
         0.49235108],
       [-0.12434592, -0.04788307, -0.08896299,  0.02832385,  0.20907454,
         0.16835376]])

In [95]:
pinv.dot(R) # should give back an identity matrix, probably with small numeric differences in off-diagnoals

array([[ 1.00000000e+00,  3.33066907e-16, -6.10622664e-16,
         0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00,  1.94289029e-16,
         2.22044605e-16],
       [-1.11022302e-16,  5.55111512e-16,  1.00000000e+00,
         5.55111512e-16],
       [-9.71445147e-17,  8.32667268e-17,  4.02455846e-16,
         1.00000000e+00]])

## Statistical modeling

Now let's look at how to use linear algebra in Python to perform statistical modeling.  We will fit the general linear model:

$ Y = X * \beta$

where Y are the data, X is the *design matrix*, and $\beta$ is a vector of model parameters.  We can estimate the parameters using the following equation:

$ \hat{\beta} = (X^T X)^{-1}X^T Y$

We would generally want to include a column of ones in the design matrix (i.e. an intercept term) in addition to the independent variables of interest, in order to fit the mean of the data.  Let's start by fitting a simple linear regression with five observations, using the following design matrix:

$X = \begin{bmatrix}
-2 & 1\\ 
-1 & 1\\ 
0 & 1\\ 
1 & 1\\ 
2 & 1
\end{bmatrix}$

The first columns reflects the linear term, and the second column reflects the intercept.  Note that we have *centered* the linear term by removing its mean.


In [107]:
X = numpy.ones((5, 2))
X[:, 0] = numpy.arange(-2, 3)
X

array([[-2.,  1.],
       [-1.,  1.],
       [ 0.,  1.],
       [ 1.,  1.],
       [ 2.,  1.]])

Let's generate some data using this model:

In [113]:
beta = numpy.array([3, 2])  # slope = 3, mean = 2
Y = X.dot(beta) 
Y

array([-4., -1.,  2.,  5.,  8.])

Now we can estimate the parameters from the data:

In [114]:
beta_hat = numpy.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)
beta_hat

array([3., 2.])

We could also use a built-in function from the statsmodels library to perfom linear regression on these data, which also provides statistics for the regression model.  Statsmodels uses a design pattern that is common in Python, where the model is first configured and then fit in a separate step.

In [118]:
model = statsmodels.api.OLS(Y, X)  # set up the model
results = model.fit()  # fit the model
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 4.721e+31
Date:                Sun, 18 Aug 2019   Prob (F-statistic):           6.80e-48
Time:                        09:19:41   Log-Likelihood:                 165.26
No. Observations:                   5   AIC:                            -326.5
Df Residuals:                       3   BIC:                            -327.3
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             3.0000   4.37e-16   6.87e+15      0.0

/Users/poldrack/anaconda3/envs/py36/lib/python3.6/site-packages/statsmodels/stats/stattools.py:72: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)
